-----[ 테이블 생성 ]-------------------------------------------------------------------------------------

-- 1.과정 테이블 생성
CREATE TABLE COURSE
(  C_CODE    VARCHAR2(10)
  ,C_NAME   VARCHAR2(40)
  ,CONSTRAINT COURSE_CODE_PK PRIMARY KEY(C_CODE)
);
--==>>Table COURSE이(가) 생성되었습니다.
ALTER TABLE COURSE
MODIFY C_NAME CONSTRAINT COURSE_NAME_NN NOT NULL; 


-- 2.과목 테이블 생성
CREATE TABLE SUBJECT
( SUB_CODE    VARCHAR2(10)
, SUB_NAME    VARCHAR2(20)
,CONSTRAINT SUBJECT_CODE_PK PRIMARY KEY(SUB_CODE)
);
--==>>Table SUBJECT이(가) 생성되었습니다.

ALTER TABLE SUBJECT
MODIFY SUB_NAME CONSTRAINT SUBJECT_NAME_NN NOT NULL; 


-- 3. 강의실 테이블 생성
CREATE TABLE ROOM
( R_CODE VARCHAR2(10)
, R_NAME VARCHAR2(10)
,CONSTRAINT ROOM_CODE_PK PRIMARY KEY(R_CODE)
);
--==>>Table ROOM이(가) 생성되었습니다.
ALTER TABLE ROOM
MODIFY R_NAME CONSTRAINT ROOM_NAME_NN NOT NULL; 


--4. 교재 테이블 생성
CREATE TABLE BOOK
( B_CODE VARCHAR2(10)
, B_NAME VARCHAR2(30)
, CONSTRAINT BOOK_CODE_PK PRIMARY KEY (B_CODE)
);
--==>> Table BOOK이(가) 생성되었습니다.
ALTER TABLE BOOK
MODIFY B_NAME CONSTRAINT BOOK_NAME_NN NOT NULL; 



-- 5. 교수 테이블 생성
CREATE TABLE PROFESSOR
( P_ID VARCHAR2(20)
, P_NAME VARCHAR2(10)
, P_SSN VARCHAR2(14) 
, P_PW VARCHAR2(30)
, CONSTRAINT PRO_ID_PK PRIMARY KEY(P_ID)
);
--==>> Table PROFESSOR이(가) 생성되었습니다.
ALTER TABLE PROFESSOR
MODIFY P_NAME CONSTRAINT PRO_NAME_NN NOT NULL; 

ALTER TABLE PROFESSOR
MODIFY P_SSN CONSTRAINT PRO_SSN_NN NOT NULL; 

ALTER TABLE PROFESSOR
MODIFY P_PW CONSTRAINT PRO_PW_NN NOT NULL; 



--6. 학생 테이블 생성
CREATE TABLE STUDENTS
( S_ID VARCHAR2(20)
, S_NAME VARCHAR2(10)
, S_SSN VARCHAR2(14)
, S_PW VARCHAR2(30)
, CONSTRAINT STU_ID_PK PRIMARY KEY(S_ID)
);
--==>> Table STUDENTS이(가) 생성되었습니다.

ALTER TABLE STUDENTS
MODIFY S_PW CONSTRAINT STU_NAME_NN NOT NULL; 

ALTER TABLE STUDENTS
MODIFY S_SSN CONSTRAINT STU_SSN_NN NOT NULL; 

ALTER TABLE STUDENTS
MODIFY S_NAME CONSTRAINT STU_NE_NN NOT NULL; 





--7,관리자 테이블 생성
CREATE TABLE MANAGER
(M_ID    VARCHAR2(20)
,M_PW   VARCHAR2(20)
,CONSTRAINT MANAGER_ID_PK PRIMARY KEY(M_ID)
);
--==>Table MANAGER이(가) 생성되었습니다
ALTER TABLE MANAGER
MODIFY M_PW CONSTRAINT STU_PW_NN NOT NULL; 


--8.개설된 과정 테이블 생성
CREATE TABLE OPEN_COURSE
(OC_CODE    VARCHAR2(10)
,OC_START   DATE
,OC_END     DATE
,R_CODE     VARCHAR2(10)
,P_ID       VARCHAR2(20)
,C_CODE     VARCHAR2(10)
,CONSTRAINT OPC_CODE_PK PRIMARY KEY(OC_CODE)
,CONSTRAINT OPC_RCODE_FK FOREIGN KEY (R_CODE)
            REFERENCES ROOM(R_CODE) ON DELETE CASCADE
,CONSTRAINT OPC_PID_FK FOREIGN KEY(P_ID)
            REFERENCES PROFESSOR(P_ID) ON DELETE CASCADE
,CONSTRAINT OPC_CCODE_FK FOREIGN KEY(C_CODE)
            REFERENCES COURSE(C_CODE) ON DELETE CASCADE

);
--==>Table OPEN_COURSE이(가) 생성되었습니다.

ALTER TABLE OPEN_COURSE
MODIFY OC_START CONSTRAINT OPC_START_NN NOT NULL; 

ALTER TABLE OPEN_COURSE
MODIFY OC_END CONSTRAINT OPC_END_NN NOT NULL; 

ALTER TABLE OPEN_COURSE
MODIFY R_CODE  CONSTRAINT OPC_RCODE_NN NOT NULL; 

ALTER TABLE OPEN_COURSE
MODIFY P_ID  CONSTRAINT OPC_PID_NN NOT NULL; 

ALTER TABLE OPEN_COURSE
MODIFY C_CODE  CONSTRAINT OPC_CCODE_NN NOT NULL; 



--9.학생별 수강신청 테이블 생성 (학생의 수강신청은 과정으로 한다.)
CREATE TABLE STUDENT_COURSE
(SC_CODE VARCHAR2(10)
,S_ID    VARCHAR2(20)
,OC_CODE VARCHAR2(10)
,SC_DATE  DATE DEFAULT SYSDATE
,CONSTRAINT STUCO_SCCODE_PK PRIMARY KEY(SC_CODE)
,CONSTRAINT STUCO_SID_FK FOREIGN KEY(S_ID) 
            REFERENCES STUDENTS(S_ID) ON DELETE CASCADE
,CONSTRAINT STUCO_OCCODE_FK FOREIGN KEY(OC_CODE)
            REFERENCES OPEN_COURSE(OC_CODE) ON DELETE CASCADE
);
--==>Table STUDENT_COURSE이(가) 생성되었습니다.
ALTER TABLE STUDENT_COURSE
MODIFY S_ID  CONSTRAINT SC_SID_NN NOT NULL; 

ALTER TABLE STUDENT_COURSE
MODIFY OC_CODE  CONSTRAINT SC_OCCODE_NN NOT NULL; 

ALTER TABLE STUDENT_COURSE
MODIFY SC_DATE  CONSTRAINT SC_DATE_NN NOT NULL;



-- 10.개설 과목 테이블
CREATE TABLE OPEN_SUBJECT
( OS_CODE VARCHAR2(10)
, SUB_CODE VARCHAR2(10)
, OS_START DATE
, OS_END   DATE
, B_CODE    VARCHAR2(10)
, OC_CODE   VARCHAR2(10)
, P_CHUL    NUMBER(10)
, P_SILGI    NUMBER(10)
, P_PILGI    NUMBER(10)
, CONSTRAINT OPS_OSCODE_PK PRIMARY KEY(OS_CODE)
, CONSTRAINT OPS_SUBCODE_FK FOREIGN KEY(SUB_CODE)
                REFERENCES SUBJECT(SUB_CODE) ON DELETE CASCADE
, CONSTRAINT OPS_BCODE_FK FOREIGN KEY(B_CODE)
                REFERENCES BOOK(B_CODE) ON DELETE CASCADE
, CONSTRAINT OPS_OCCODE_FK FOREIGN KEY(OC_CODE)
                REFERENCES OPEN_COURSE(OC_CODE) ON DELETE CASCADE
,CONSTRAINT OS_P_CH CHECK(P_CHUL + P_PILGI + P_SILGI = 100)
);
--==>> Table OPEN_SUBJECT이(가) 생성되었습니다.
ALTER TABLE OPEN_SUBJECT
MODIFY SUB_CODE  CONSTRAINT OS_SUBCODE_NN NOT NULL;

ALTER TABLE OPEN_SUBJECT
MODIFY OS_START  CONSTRAINT OS_STRAT_NN NOT NULL;

ALTER TABLE OPEN_SUBJECT
MODIFY OS_END  CONSTRAINT OS_END_NN NOT NULL;

ALTER TABLE OPEN_SUBJECT
MODIFY B_CODE  CONSTRAINT OS_BCODE_NN NOT NULL;

ALTER TABLE OPEN_SUBJECT
MODIFY OC_CODE  CONSTRAINT OS_OCCODE_NN NOT NULL;

-- 11.성적 테이블
CREATE TABLE GRADE
( GRADE_CODE VARCHAR2(10)
, SC_CODE    VARCHAR2(10)
, OS_CODE    VARCHAR2(10)
, S_CHUL     NUMBER(3)
, S_SILGI    NUMBER(3)
, S_PILGI    NUMBER(3)
, CONSTRAINT GRADE_GCODE_PK PRIMARY KEY(GRADE_CODE)
, CONSTRAINT GRADE_SCCODE_FK FOREIGN KEY(SC_CODE) 
                REFERENCES STUDENT_COURSE(SC_CODE) ON DELETE CASCADE
, CONSTRAINT GRADE_OSCODE_FK FOREIGN KEY(OS_CODE)
                REFERENCES OPEN_SUBJECT(OS_CODE) ON DELETE CASCADE
,CONSTRAINT GRADE_S_CH CHECK(S_CHUL + S_PILGI + S_SILGI BETWEEN 0 AND 100)
);
--==>> Table GRADE이(가) 생성되었습니다.
ALTER TABLE GRADE
MODIFY SC_CODE  CONSTRAINT G_SCCODE_NN NOT NULL;

ALTER TABLE GRADE
MODIFY OS_CODE   CONSTRAINT G_OSCODE_NN NOT NULL;




-- 12. 중도탈락 학생 테이블
CREATE TABLE DROP_STUDENTS
( DS_CODE   VARCHAR2(10)
, D_DATE    DATE DEFAULT SYSDATE
, SC_CODE   VARCHAR2(10)
, CONSTRAINT DROPS_DSCODE_PK PRIMARY KEY(DS_CODE)
, CONSTRAINT DEOPS_SCCODE_FK FOREIGN KEY(SC_CODE)
                REFERENCES STUDENT_COURSE(SC_CODE) ON DELETE CASCADE
);
--==>> Table DROP_STUDENTS이(가) 생성되었습니다.

ALTER TABLE DROP_STUDENTS
MODIFY D_DATE   CONSTRAINT DROPS_DATE_NN NOT NULL;

ALTER TABLE DROP_STUDENTS
MODIFY SC_CODE   CONSTRAINT DROPS_SCCODE_NN NOT NULL;






