-- TEAM4 계정 생성 후 준 권한----

CREATE USER TEAM_4 IDENTIFIED BY java006$;
GRANT CREATE TABLE TO TEAM_4;

GRANT CREATE SESSION TO TEAM_4;

GRANT CONNECT TO TEAM_4;

GRANT RESOURCE,UNLIMITED TABLESPACE TO TEAM_4;

CREATE TABLESPACE TBS_TEAM4
DATAFILE 'C:\OracleStudy\TEAM_4\TBS_TEAM401,DBF'
SIZE 4M
EXTENT MANAGEMENT LOCAL
SEGMENT SPACE MANAGEMENT AUTO;


GRANT CREATE TABLE TO TEAM_4;

ALTER USER TEAM_4
QUOTA UNLIMITED ON TBS_TEAM4;


GRANT CREATE PROCEDURE TO TEAM_4;


